FROM node:20-alpine

WORKDIR /app

# Install deps
COPY package*.json ./
RUN npm install

# Copy source and build frontend
COPY . .
RUN npm run build

# Install a static file server
RUN npm install -g serve

# Serve the Vite build
#CMD ["serve", "-s", "dist", "-l", "0.0.0.0:5713"]
CMD ["serve", "-s", "dist", "--listen", "5713"]
#CMD ["npm", "run", "dev", "--", "--host"]
EXPOSE 5713
